name: jack
version: 0.1.0
authors:
- Igor Borges <igor@borges.me>
description: >
  Jack.
homepage: https://github.com/Igor1201/jack

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  intl: ^0.15.7
  petitparser: ^2.0.2

dev_dependencies:
  test: ^1.0.0
