name: jack
version: 0.2.1

description: >
  Jack.
homepage: https://github.com/comigor/jack
publish_to: none

environment:
  sdk: ">=2.8.0 <3.0.0"
  # sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  intl: ^0.17.0-nullsafety.2
  petitparser: ^4.0.0-nullsafety
  money2:
    git:
      url: git@github.com:comigor/money.dart.git
      ref: nnbd-bugfix
  freezed_annotation:

dev_dependencies:
  test: ^1.16.0-nullsafety.11
  pedantic: ^1.10.0-nullsafety.3
  build_runner:
  freezed:
