name: jack
version: 0.1.1

description: >
  Jack.
homepage: https://github.com/comigor/jack

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  petitparser: ^3.1.0

dev_dependencies:
  test: ^1.15.4
  pedantic: ^1.9.2
