name: jack
version: 0.4.1-nullsafety.0

description: >
  Jack.
homepage: https://github.com/comigor/jack

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  intl: ^0.17.0-nullsafety
  petitparser: ^4.0.0-nullsafety
  meta: ^1.3.0-nullsafety
  money2: ^2.0.1-nullsafety
  freezed_annotation:

dev_dependencies:
  test: ^1.16.0-nullsafety
  pedantic: ^1.10.0-nullsafety
  build_runner:
  freezed:
