name: jack
version: 0.3.2

description: >
  Jack.
homepage: https://github.com/comigor/jack

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  petitparser: ^3.1.0
  meta: ^1.2.4
  # money2: ^1.4.3
  money2:
    git:
      url: https://github.com/comigor/money.dart.git
      ref: precision-0
  freezed_annotation:

dev_dependencies:
  test: ^1.15.4
  pedantic: ^1.9.2
  build_runner:
  freezed:
