on: pull_request

name: CI

jobs:
  check-version-and-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/check-version-and-changelog
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          base_ref: "${{ github.base_ref }}"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/dart-test
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          exclude_regex: "example"
